from django.urls import path
from Oncoliq.views import *
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('', loginWeb),
    path('inicio/', inicio, name="inicio"),
    path('laboratorio/', laboratorio, name="Laboratorio"),
    path('medico/', medico, name="Medico"),
    path('paciente/', paciente, name="Paciente"),
    path('setLaboratorio/', setLaboratorio, name="setLaboratorio"),
    path('getLaboratorio/', getLaboratorio, name="getLaboratorio"),
    path('buscarLaboratorio/', buscarLaboratorio, name="buscarLaboratorio"),
    path('setMedico/', setMedico, name="setMedico"),
    path('getMedico/', getMedico, name="getMedico"),
    path('buscarMedico/', buscarMedico, name="buscarMedico"),
    path('setPaciente/', setPaciente, name="setPaciente"),
    path('getPaciente/', getPaciente, name="getPaciente"),
    path('buscarPaciente/', buscarPaciente, name="buscarPaciente"),
    path('eliminarLaboratorio/<int:pk>/', eliminarLaboratorio, name='eliminarLaboratorio'),
    path('editarLaboratorio/<int:pk>/', editarLaboratorio, name="editarLaboratorio"),
    path('detalleLaboratorio/<int:pk>/', detalleLaboratorio, name='detalleLaboratorio'),
    path('eliminarMedico/<int:pk>/', eliminarMedico, name='eliminarMedico'),
    path('editarMedico/<int:pk>/', editarMedico, name="editarMedico"),
    path('detalleMedico/<int:pk>/', detalleMedico, name='detalleMedico'),
    path('eliminarPaciente/<int:pk>/', eliminarPaciente, name='eliminarPaciente'),
    path('editarPaciente/<int:pk>/', editarPaciente, name="editarPaciente"),
    path('detallePaciente/<int:pk>/', detallePaciente, name='detallePaciente'),
    path('login/', loginWeb, name="login"),
    path('registro/', registro, name="registro"),
    path('logout/', LogoutView.as_view(template_name = 'Oncoliq/login.html'), name="logout"),
    path('perfil/', perfilview, name="perfil"),
    path('Perfil/editarPerfil/', editarPerfil, name="editarPerfil"),
    path('Perfil/changePassword/', changePassword, name="changePassword"),
    path('Perfil/changeAvatar/', editAvatar, name="editAvatar"),
    path('comentario/', ComentarioPagina.as_view(), name="comentario"),
    path('comentarios/', mostrarComentarios, name='mostrarComentarios'),
    path('acercaDeMi/', views.about, name='acercaDeMi'),
]