# Generated by Django 4.2.2 on 2023-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oncoliq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='informe',
            field=models.CharField(max_length=200),
        ),
    ]
