# Generated by Django 4.2.2 on 2023-06-26 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Oncoliq', '0002_alter_medico_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
